name: Like
main: amata1219.like.Main
version: '${version}'
depend:
  - Vault
  - PCGF_PluginLib
softdepend:
  - DecentHolograms
api-version: 1.18
author: '@amata1219, tererun'

default-permission-message: &denied You don't have <permission>
commands:
  like:
    permission: like.like
    permission-message: *denied
  likec:
    permission: like.like
    permission-message: *denied
  likel:
    permission: like.like
    permission-message: *denied
  likes:
    permission: like.like
    permission-message: *denied
  liketoken:
    permission: like.like
    permission-message: *denied
  likeb:
    permission: like.like
    permission-message: *denied
  likerandom:
    permission: like.like
    permission-message: *denied
    aliases: [likerd]
  liket:
    permission: like.like
    permission-message: *denied
  likesearch:
    permission: like.like
    permission-message: *denied
    aliases: [likesc]
  likeorscu:
    description: "orscu = Open Range Search Confirmation UI"
    permission: like.like
    permission-message: *denied
  likeop:
    permission: like.likeop
    permission-message: *denied